require("../app/components/nav-bar/nav-bar.story")
require("../app/components/registration-form/registration-form.story")
require("../app/components/password-field/password-field.story")
require("../app/components/loading-wheel/loading-wheel.story")
require("../app/components/text-field/text-field.story")
require("../app/components/login-form/login-form.story")
require("../app/components/text/text.story")
require("../app/components/button/button.story")
